### ISSUE TITLE
Template Not Found when using dust engine

### ISSUE THREAD

**Issue by AleCaste** [krakenjs/bundalo#12]
Hello!
We are getting error 'Template not found' when bundalo is set to work with 'dust' engine.
If bundalo is set to work with 'none' engine, we get the data alright without any errors.

We tried to set cache to false to see if that made any difference and still we got the error.

The bundle is a '.properties' file and we have made sure the file exists in the right folder.
When we delete the file and run the application we get a different error:```{ [Error: EISDIR, read] errno: -4068, code: 'EISDIR' }```  so that tells us the problem is somewhere else.

Anything we are missing?

**Comment by aredridel** [comment]
Is there a reason you're trying to read properties with a dust reader?

Dust reader reads templates, not properties.

**Comment by AleCaste** [comment]
The values for each key in the properties file are dust templates themselves so that we can inject values. E.g.

greeting=Hello {name}

Isn't this how it is supposed to work? Just asking

**Comment by aredridel** [comment]
Oh, I stand corrected. My apologies. Yes, the dust engine should work for that. 

What's the configuration for bundalo you're passing it?

**Comment by AleCaste** [comment]
This one:
```
{
  'fallback': 'en-US',
  'contentPath': 'locales/',
  'engine': 'dust',
  'cache': false
}
```

As I commented earlier, bundalo can locate the .properties file just fine, it's when it has to use Dust when it fails.
One thing we don't understand is why to pass a model to the whole bundle. It makes sense to pass a model to individual keys you want to retrieve, but not to the whole .properties file.
That said, bundalo should expose an additional synchronous method to retrieve the value of just one key (it could use the cache etc) given a model for it.

**Comment by aredridel** [comment]
Yeah. There are more contortions to do when dust is involved.

Can you try an absolute path like `path.join(__dirname, 'locales')` ?

**Comment by AleCaste** [comment]
We have tried that to (using an absolute path) and it threw the same error.

**Comment by aredridel** [comment]
>  One thing we don't understand is why to pass a model to the whole bundle. It makes sense to pass a model to individual keys you want to retrieve, but not to the whole .properties file.

You've got a lot of models live at once you want to fetch properties for?

> That said, bundalo should expose an additional synchronous method to retrieve the value of just one key (it could use the cache etc) given a model for it.

That would only add new error cases, when something isn't in cache, and starts involving complexities like NTTLs.

**Comment by aredridel** [comment]
What's your file tree look like? And the call to fetch the data?

**Comment by AleCaste** [comment]
The file tree:
```
[root]
  node_app
    locales
      US
        en
          shared
            cookie_policy.properties
      ES
        es
          shared
            cookie_policy.properties
```
The call:
```
bundalo.get({
  bundle: 'shared/cookie_policy',
  locality: 'en-US',
  model: null
},
function(err, data) {
  console.log('data:', data, '   err:', err);
});
```
So in a real-life scenario. How this library could be used if we want to retrieve values for several keys in a bundle, using models in the process?
Can bundalo do that or we just need something else or add our own extra code?

**Comment by aredridel** [comment]
If you've multiple models, make multiple calls.

(If I had my way, I'd eliminate the multi-call interface, and switch to using promises for this.)
