### ISSUE TITLE
Locale property folders have hyphen separated names

### ISSUE THREAD

**Issue by raghavgujjar** [krakenjs/bundalo#14]
I have a use case where folder names are hyphen separated.
Eg: I have GROUPA-EMEA-LUX. I also have GROUPA. So, currently if I pass something like en-GROUPA-EMEA-LUX or en_GROUPA-EMEA-LUX it still treats it as en-GROUPA. Should I consider naming the folder differently? If so, what separator do you suggest? Or, is there something that can be fixed in the resolver?

**Comment by aredridel** [comment]
I think you want to pass the locale to the resolver as an object. This abuses the semantics somewhat but will work for now.

`{ language: 'en', country: 'GROUPA-EMEA-LUX' }`. This avoids the parsing. When I add support for `formatPath` in #15, that function can do proper mapping -- you'd use the real locale as input, and do the mapping to a grouped path in the formatPath function. 

That will be a new major, likely.
